import {
  collection,
  addDoc,
  doc,
  updateDoc,
  deleteDoc,
} from "firebase/firestore";
import { db } from "./config";

/**
 * Function that save a new task in the database
 * @param {object} data
 * @returns
 * if the transaction is successful, return the new task id generated by the db
 * if the transaction failed, return null
 */
export async function save(data) {
  try {
    const docRef = await addDoc(collection(db, "tasks"), data);
    return docRef.id;
  } catch (error) {
    console.log("Error adding document: ", error);
    return null;
  }
}

/**
 * Function that update any change in the tasks
 * @param {string} id
 * @param {object} data
 * @returns
 * if the transaction is successful, return true; if not, false
 */
export async function update(id, data) {
  try {
    const docRef = doc(db, "tasks", id);
    await updateDoc(docRef, data);
    return true;
  } catch {
    return false;
  }
}

/**
 * Function that remove a task based on its id
 * @param {string} id
 * @returns
 * if the removing is successful, return true; if not, false
 */
export async function remove(id) {
  try {
    await deleteDoc(doc(db, "tasks", id));
    return true;
  } catch {
    return false;
  }
}

/**
 * Function that delete all tasks with the id inside the array ids
 * @param {array} ids
 * @returns
 * if the removing is successful, return true; if not, false
 */
export async function removeAll(ids) {
  try {
    ids.forEach((id) => {
      remove(id);
    });
    return true;
  } catch {
    return false;
  }
}
